
// Company name mappings for dividend stocks
export const getCompanyName = (symbol: string): string => {
  const companyNames: Record<string, string> = {
    'AAPL': 'Apple Inc.',
    'MSFT': 'Microsoft Corporation',
    'JNJ': 'Johnson & Johnson',
    'PG': 'Procter & Gamble',
    'KO': 'Coca-Cola Company',
    'PEP': 'PepsiCo Inc.',
    'WMT': 'Walmart Inc.',
    'MCD': "McDonald's Corporation",
    'VZ': 'Verizon Communications',
    'T': 'AT&T Inc.',
    'XOM': 'Exxon Mobil Corporation',
    'CVX': 'Chevron Corporation',
    'IBM': 'International Business Machines',
    'INTC': 'Intel Corporation',
    'COST': 'Costco Wholesale',
    'JPM': 'JPMorgan Chase & Co.',
    'BAC': 'Bank of America',
    'HD': 'Home Depot Inc.',
    'ARCC': 'Ares Capital Corporation',
    'O': 'Realty Income Corporation',
    'META': 'Meta Platforms Inc.',
    'NVDA': 'NVIDIA Corporation',
    'UNH': 'UnitedHealth Group',
    'PFE': 'Pfizer Inc.',
    'ABT': 'Abbott Laboratories',
    'TMO': 'Thermo Fisher Scientific',
    'MRK': 'Merck & Co.',
    'LOW': 'Lowe\'s Companies',
    'TGT': 'Target Corporation',
    'UL': 'Unilever PLC',
    'CL': 'Colgate-Palmolive',
    'KMB': 'Kimberly-Clark',
    'GIS': 'General Mills',
    'K': 'Kellogg Company',
    'CPB': 'Campbell Soup Company',
    'WFC': 'Wells Fargo & Co.',
    'C': 'Citigroup Inc.',
    'GS': 'Goldman Sachs Group',
    'MS': 'Morgan Stanley',
    'AXP': 'American Express',
    'V': 'Visa Inc.',
    'MA': 'Mastercard Inc.',
    'BLK': 'BlackRock Inc.',
    'SPG': 'Simon Property Group',
    'SO': 'Southern Company',
    'D': 'Dominion Energy',
    'DUK': 'Duke Energy',
    'NEE': 'NextEra Energy',
    'AEP': 'American Electric Power',
    'EXC': 'Exelon Corporation',
    'COP': 'ConocoPhillips',
    'EOG': 'EOG Resources',
    'KMI': 'Kinder Morgan',
    'ENB': 'Enbridge Inc.',
    'TC': 'TC Energy',
    'SLB': 'Schlumberger',
    'CAT': 'Caterpillar Inc.',
    'HON': 'Honeywell International',
    'GE': 'General Electric',
    'LMT': 'Lockheed Martin',
    'RTX': 'Raytheon Technologies',
    'UPS': 'United Parcel Service',
    'FDX': 'FedEx Corporation',
    'EMR': 'Emerson Electric',
    'NKE': 'Nike Inc.',
    'SBUX': 'Starbucks Corporation',
    'MO': 'Altria Group',
    'PM': 'Philip Morris International',
    'BTI': 'British American Tobacco',
    'DD': 'DuPont de Nemours',
    'DOW': 'Dow Inc.',
    'LYB': 'LyondellBasell Industries',
    'FCX': 'Freeport-McMoRan',
    'NEM': 'Newmont Corporation',
    'MAIN': 'Main Street Capital',
    'STAG': 'STAG Industrial',
    'PLD': 'Prologis Inc.',
    'EXR': 'Extended Stay America',
    'PSA': 'Public Storage',
    'AMT': 'American Tower',
    'CCI': 'Crown Castle',
    'ASML': 'ASML Holding',
    'NESN': 'Nestlé S.A.',
    'NOVN': 'Novartis AG',
    'ROG': 'Roche Holding AG',
    'SAP': 'SAP SE',
    'SHEL': 'Shell plc',
    'BP': 'BP p.l.c.',
    'VOD': 'Vodafone Group',
    'SPY': 'SPDR S&P 500 ETF',
    'VTI': 'Vanguard Total Stock Market ETF',
    'VOO': 'Vanguard S&P 500 ETF',
    'QQQ': 'Invesco QQQ Trust',
    'IWM': 'iShares Russell 2000 ETF',
    'EFA': 'iShares MSCI EAFE ETF',
    'VEA': 'Vanguard FTSE Developed Markets ETF',
    'IEMG': 'iShares Core MSCI Emerging Markets ETF',
    'VWO': 'Vanguard FTSE Emerging Markets ETF',
    'SCHD': 'Schwab US Dividend Equity ETF',
    'VYM': 'Vanguard High Dividend Yield ETF',
    'NOBL': 'ProShares S&P 500 Dividend Aristocrats ETF',
    'VIG': 'Vanguard Dividend Appreciation ETF',
    'DGRO': 'iShares Core Dividend Growth ETF',
    'HDV': 'iShares High Dividend ETF',
    'DVY': 'iShares Select Dividend ETF',
    'MMM': '3M Company',
    'ITW': 'Illinois Tool Works',
    'TXN': 'Texas Instruments',
    'QCOM': 'Qualcomm Inc.',
    'AVGO': 'Broadcom Inc.',
    'ABBV': 'AbbVie Inc.',
    'GILD': 'Gilead Sciences',
    'LLY': 'Eli Lilly and Company',
    'AMGN': 'Amgen Inc.',
    'CVS': 'CVS Health',
    'MDT': 'Medtronic plc',
    'DHR': 'Danaher Corporation',
    'MDLZ': 'Mondelez International',
    'HSY': 'The Hershey Company',
    'KR': 'The Kroger Co.',
    'SYY': 'Sysco Corporation',
    'YUM': 'Yum! Brands',
    'USB': 'U.S. Bancorp',
    'TFC': 'Truist Financial',
    'PNC': 'PNC Financial Services',
    'COF': 'Capital One Financial',
    'SCHW': 'Charles Schwab Corporation',
    'BK': 'The Bank of New York Mellon',
    'STT': 'State Street Corporation',
    'XEL': 'Xcel Energy',
    'ED': 'Consolidated Edison',
    'ETR': 'Entergy Corporation',
    'ES': 'Eversource Energy',
    'FE': 'FirstEnergy Corp.',
    'PPL': 'PPL Corporation',
    'WMB': 'Williams Companies',
    'OKE': 'ONEOK Inc.',
    'EPD': 'Enterprise Products Partners',
    'ET': 'Energy Transfer LP',
    'MMP': 'Magellan Midstream Partners',
    'TRP': 'TC Energy Corporation',
    'DE': 'Deere & Company',
    'BA': 'Boeing Company',
    'NOC': 'Northrop Grumman',
    'GD': 'General Dynamics',
    'LHX': 'L3Harris Technologies',
    'F': 'Ford Motor Company',
    'GM': 'General Motors',
    'TJX': 'TJX Companies',
    'RCL': 'Royal Caribbean Cruises',
    'CCL': 'Carnival Corporation',
    'NUE': 'Nucor Corporation',
    'STLD': 'Steel Dynamics',
    'PKG': 'Packaging Corporation of America',
    'IP': 'International Paper',
    'APD': 'Air Products and Chemicals',
    'LIN': 'Linde plc',
    'ECL': 'Ecolab Inc.',
    'DLR': 'Digital Realty Trust',
    'VTR': 'Ventas Inc.',
    'WELL': 'Welltower Inc.',
    'AVB': 'AvalonBay Communities',
    'EQR': 'Equity Residential',
    'MAA': 'Mid-America Apartment Communities',
    'ESS': 'Essex Property Trust',
    'UDR': 'UDR Inc.',
    'CPT': 'Camden Property Trust',
    'HST': 'Host Hotels & Resorts',
    'FRT': 'Federal Realty Investment Trust',
    'REG': 'Regency Centers',
    'BXP': 'Boston Properties',
    'KIM': 'Kimco Realty',
    'EQIX': 'Equinix Inc.',
    'UNVR': 'Unilever NV',
    'TTE': 'TotalEnergies SE',
    'ENGI': 'Engie SA',
    'OR': "L'Oreal SA",
    'SAN': 'Banco Santander SA',
    'BBVA': 'Banco Bilbao Vizcaya Argentaria',
    'BNP': 'BNP Paribas SA',
    'ING': 'ING Groep NV',
    'DTE': 'DTE Energy',
    'ENI': 'Eni SpA',
    'JEPI': 'JPMorgan Equity Premium Income ETF',
    'JEPQ': 'JPMorgan Nasdaq Equity Premium Income ETF',
    'SPLG': 'SPDR Portfolio S&P 500 ETF',
    'VT': 'Vanguard Total World Stock ETF',
    'VXUS': 'Vanguard Total International Stock ETF',
    'DIVO': 'Amplify CWP Enhanced Dividend Income ETF',
    'SPHD': 'Invesco S&P 500 High Dividend Low Volatility ETF',
    'SCHY': 'Schwab International Dividend Equity ETF',
    'SPYD': 'SPDR Portfolio S&P 500 High Dividend ETF'
  };
  
  return companyNames[symbol] || symbol;
};
