
// Core dividend data for major dividend-paying stocks
export interface DividendInfo {
  annual: number;
  quarterly: number;
  yield: number;
  frequency: 'quarterly' | 'annual' | 'monthly' | 'semi-annual';
}

export const DIVIDEND_DATABASE: Record<string, DividendInfo> = {
  // Technology
  'AAPL': { annual: 0.96, quarterly: 0.24, yield: 0.49, frequency: 'quarterly' },
  'MSFT': { annual: 3.00, quarterly: 0.75, yield: 0.72, frequency: 'quarterly' },
  'INTC': { annual: 0.50, quarterly: 0.125, yield: 2.1, frequency: 'quarterly' },
  'IBM': { annual: 6.63, quarterly: 1.6575, yield: 3.5, frequency: 'quarterly' },
  'ORCL': { annual: 1.60, quarterly: 0.40, yield: 1.2, frequency: 'quarterly' },
  'CSCO': { annual: 1.60, quarterly: 0.40, yield: 3.0, frequency: 'quarterly' },
  'TXN': { annual: 5.20, quarterly: 1.30, yield: 2.8, frequency: 'quarterly' },
  'QCOM': { annual: 3.04, quarterly: 0.76, yield: 2.2, frequency: 'quarterly' },
  'AVGO': { annual: 20.40, quarterly: 5.10, yield: 1.9, frequency: 'quarterly' },
  'ADBE': { annual: 0, quarterly: 0, yield: 0, frequency: 'quarterly' },
  
  // Healthcare & Pharmaceuticals
  'JNJ': { annual: 4.76, quarterly: 1.19, yield: 3.1, frequency: 'quarterly' },
  'UNH': { annual: 7.52, quarterly: 1.88, yield: 1.3, frequency: 'quarterly' },
  'PFE': { annual: 1.64, quarterly: 0.41, yield: 6.2, frequency: 'quarterly' },
  'ABT': { annual: 2.16, quarterly: 0.54, yield: 1.8, frequency: 'quarterly' },
  'TMO': { annual: 1.20, quarterly: 0.30, yield: 0.2, frequency: 'quarterly' },
  'MRK': { annual: 2.80, quarterly: 0.70, yield: 2.7, frequency: 'quarterly' },
  'AZN': { annual: 1.90, quarterly: 0.475, yield: 2.8, frequency: 'quarterly' },
  'GSK': { annual: 2.04, quarterly: 0.51, yield: 4.1, frequency: 'quarterly' },
  'BMY': { annual: 2.04, quarterly: 0.51, yield: 4.8, frequency: 'quarterly' },
  'GILD': { annual: 3.04, quarterly: 0.76, yield: 4.2, frequency: 'quarterly' },
  'LLY': { annual: 4.40, quarterly: 1.10, yield: 1.2, frequency: 'quarterly' },
  'ABBV': { annual: 6.20, quarterly: 1.55, yield: 3.4, frequency: 'quarterly' },
  'AMGN': { annual: 8.08, quarterly: 2.02, yield: 3.1, frequency: 'quarterly' },
  'CVS': { annual: 2.20, quarterly: 0.55, yield: 3.2, frequency: 'quarterly' },
  'MDT': { annual: 2.72, quarterly: 0.68, yield: 3.8, frequency: 'quarterly' },
  'DHR': { annual: 1.00, quarterly: 0.25, yield: 0.4, frequency: 'quarterly' },
  
  // Consumer Goods & Services
  'PG': { annual: 3.76, quarterly: 0.94, yield: 2.4, frequency: 'quarterly' },
  'KO': { annual: 1.84, quarterly: 0.46, yield: 3.0, frequency: 'quarterly' },
  'PEP': { annual: 4.42, quarterly: 1.105, yield: 2.8, frequency: 'quarterly' },
  'MCD': { annual: 6.08, quarterly: 1.52, yield: 2.2, frequency: 'quarterly' },
  'WMT': { annual: 2.28, quarterly: 0.57, yield: 3.0, frequency: 'quarterly' },
  'COST': { annual: 4.48, quarterly: 1.12, yield: 0.45, frequency: 'quarterly' },
  'TGT': { annual: 4.16, quarterly: 1.04, yield: 2.9, frequency: 'quarterly' },
  'UL': { annual: 1.96, quarterly: 0.49, yield: 3.4, frequency: 'quarterly' },
  'CL': { annual: 1.88, quarterly: 0.47, yield: 2.4, frequency: 'quarterly' },
  'KMB': { annual: 4.72, quarterly: 1.18, yield: 3.6, frequency: 'quarterly' },
  'GIS': { annual: 2.04, quarterly: 0.51, yield: 3.1, frequency: 'quarterly' },
  'K': { annual: 2.32, quarterly: 0.58, yield: 4.2, frequency: 'quarterly' },
  'CPB': { annual: 1.48, quarterly: 0.37, yield: 3.3, frequency: 'quarterly' },
  'KHC': { annual: 1.60, quarterly: 0.40, yield: 4.8, frequency: 'quarterly' },
  'MDLZ': { annual: 1.58, quarterly: 0.395, yield: 2.2, frequency: 'quarterly' },
  'HSY': { annual: 4.08, quarterly: 1.02, yield: 2.1, frequency: 'quarterly' },
  'KR': { annual: 1.04, quarterly: 0.26, yield: 2.2, frequency: 'quarterly' },
  'SYY': { annual: 2.00, quarterly: 0.50, yield: 2.5, frequency: 'quarterly' },
  'YUM': { annual: 2.20, quarterly: 0.55, yield: 1.6, frequency: 'quarterly' },
  
  // Financial Services
  'JPM': { annual: 4.80, quarterly: 1.20, yield: 2.4, frequency: 'quarterly' },
  'BAC': { annual: 0.96, quarterly: 0.24, yield: 2.8, frequency: 'quarterly' },
  'WFC': { annual: 1.20, quarterly: 0.30, yield: 2.9, frequency: 'quarterly' },
  'C': { annual: 2.04, quarterly: 0.51, yield: 3.2, frequency: 'quarterly' },
  'GS': { annual: 10.00, quarterly: 2.50, yield: 2.9, frequency: 'quarterly' },
  'MS': { annual: 3.70, quarterly: 0.925, yield: 4.2, frequency: 'quarterly' },
  'AXP': { annual: 2.40, quarterly: 0.60, yield: 1.3, frequency: 'quarterly' },
  'V': { annual: 1.80, quarterly: 0.45, yield: 0.7, frequency: 'quarterly' },
  'MA': { annual: 2.24, quarterly: 0.56, yield: 0.5, frequency: 'quarterly' },
  'BLK': { annual: 20.20, quarterly: 5.05, yield: 2.4, frequency: 'quarterly' },
  'SPG': { annual: 5.60, quarterly: 1.40, yield: 4.1, frequency: 'quarterly' },
  'USB': { annual: 1.76, quarterly: 0.44, yield: 4.1, frequency: 'quarterly' },
  'TFC': { annual: 2.08, quarterly: 0.52, yield: 5.2, frequency: 'quarterly' },
  'PNC': { annual: 5.60, quarterly: 1.40, yield: 3.8, frequency: 'quarterly' },
  'COF': { annual: 2.40, quarterly: 0.60, yield: 1.8, frequency: 'quarterly' },
  'SCHW': { annual: 0.88, quarterly: 0.22, yield: 1.3, frequency: 'quarterly' },
  'BK': { annual: 1.52, quarterly: 0.38, yield: 2.7, frequency: 'quarterly' },
  'STT': { annual: 2.28, quarterly: 0.57, yield: 3.2, frequency: 'quarterly' },
  
  // Utilities & Infrastructure
  'VZ': { annual: 2.56, quarterly: 0.64, yield: 6.8, frequency: 'quarterly' },
  'T': { annual: 1.11, quarterly: 0.2775, yield: 7.4, frequency: 'quarterly' },
  'SO': { annual: 2.80, quarterly: 0.70, yield: 3.8, frequency: 'quarterly' },
  'D': { annual: 4.32, quarterly: 1.08, yield: 4.1, frequency: 'quarterly' },
  'DUK': { annual: 4.02, quarterly: 1.005, yield: 4.0, frequency: 'quarterly' },
  'NEE': { annual: 1.85, quarterly: 0.4625, yield: 2.8, frequency: 'quarterly' },
  'AEP': { annual: 3.28, quarterly: 0.82, yield: 3.7, frequency: 'quarterly' },
  'EXC': { annual: 1.61, quarterly: 0.4025, yield: 4.1, frequency: 'quarterly' },
  'XEL': { annual: 1.88, quarterly: 0.47, yield: 2.8, frequency: 'quarterly' },
  'ED': { annual: 3.12, quarterly: 0.78, yield: 3.5, frequency: 'quarterly' },
  'ETR': { annual: 4.16, quarterly: 1.04, yield: 3.8, frequency: 'quarterly' },
  'ES': { annual: 1.68, quarterly: 0.42, yield: 2.1, frequency: 'quarterly' },
  'FE': { annual: 1.56, quarterly: 0.39, yield: 4.0, frequency: 'quarterly' },
  'PPL': { annual: 0.84, quarterly: 0.21, yield: 3.1, frequency: 'quarterly' },
  
  // Energy
  'XOM': { annual: 3.64, quarterly: 0.91, yield: 5.8, frequency: 'quarterly' },
  'CVX': { annual: 6.04, quarterly: 1.51, yield: 3.4, frequency: 'quarterly' },
  'COP': { annual: 2.04, quarterly: 0.51, yield: 1.8, frequency: 'quarterly' },
  'EOG': { annual: 3.00, quarterly: 0.75, yield: 2.4, frequency: 'quarterly' },
  'KMI': { annual: 1.13, quarterly: 0.2825, yield: 6.8, frequency: 'quarterly' },
  'ENB': { annual: 1.55, quarterly: 0.3875, yield: 6.2, frequency: 'quarterly' },
  'TC': { annual: 3.48, quarterly: 0.87, yield: 6.1, frequency: 'quarterly' },
  'SLB': { annual: 0.80, quarterly: 0.20, yield: 1.8, frequency: 'quarterly' },
  'TRP': { annual: 3.48, quarterly: 0.87, yield: 5.9, frequency: 'quarterly' },
  'WMB': { annual: 1.74, quarterly: 0.435, yield: 5.4, frequency: 'quarterly' },
  'OKE': { annual: 4.02, quarterly: 1.005, yield: 6.8, frequency: 'quarterly' },
  'EPD': { annual: 1.20, quarterly: 0.30, yield: 8.2, frequency: 'quarterly' },
  'ET': { annual: 1.22, quarterly: 0.305, yield: 8.9, frequency: 'quarterly' },
  'MMP': { annual: 2.94, quarterly: 0.735, yield: 6.1, frequency: 'quarterly' },
  
  // Industrial
  'MMM': { annual: 6.00, quarterly: 1.50, yield: 4.8, frequency: 'quarterly' },
  'CAT': { annual: 4.80, quarterly: 1.20, yield: 1.8, frequency: 'quarterly' },
  'HON': { annual: 4.04, quarterly: 1.01, yield: 1.9, frequency: 'quarterly' },
  'GE': { annual: 0.16, quarterly: 0.04, yield: 0.1, frequency: 'quarterly' },
  'LMT': { annual: 12.00, quarterly: 3.00, yield: 2.8, frequency: 'quarterly' },
  'RTX': { annual: 2.04, quarterly: 0.51, yield: 2.3, frequency: 'quarterly' },
  'UPS': { annual: 5.52, quarterly: 1.38, yield: 3.9, frequency: 'quarterly' },
  'FDX': { annual: 3.00, quarterly: 0.75, yield: 1.2, frequency: 'quarterly' },
  'EMR': { annual: 2.04, quarterly: 0.51, yield: 2.0, frequency: 'quarterly' },
  'ITW': { annual: 4.88, quarterly: 1.22, yield: 2.0, frequency: 'quarterly' },
  'DE': { annual: 4.90, quarterly: 1.225, yield: 1.2, frequency: 'quarterly' },
  'BA': { annual: 0, quarterly: 0, yield: 0, frequency: 'quarterly' },
  'NOC': { annual: 7.40, quarterly: 1.85, yield: 1.5, frequency: 'quarterly' },
  'GD': { annual: 4.88, quarterly: 1.22, yield: 1.8, frequency: 'quarterly' },
  'LHX': { annual: 4.00, quarterly: 1.00, yield: 1.8, frequency: 'quarterly' },
  
  // Consumer Discretionary
  'HD': { annual: 8.36, quarterly: 2.09, yield: 2.3, frequency: 'quarterly' },
  'LOW': { annual: 4.20, quarterly: 1.05, yield: 1.7, frequency: 'quarterly' },
  'NKE': { annual: 1.48, quarterly: 0.37, yield: 1.8, frequency: 'quarterly' },
  'SBUX': { annual: 2.16, quarterly: 0.54, yield: 2.3, frequency: 'quarterly' },
  'DIS': { annual: 0, quarterly: 0, yield: 0, frequency: 'quarterly' },
  'MO': { annual: 3.76, quarterly: 0.94, yield: 8.1, frequency: 'quarterly' },
  'PM': { annual: 5.20, quarterly: 1.30, yield: 5.1, frequency: 'quarterly' },
  'BTI': { annual: 2.96, quarterly: 0.74, yield: 8.4, frequency: 'quarterly' },
  'F': { annual: 0.60, quarterly: 0.15, yield: 5.1, frequency: 'quarterly' },
  'GM': { annual: 1.52, quarterly: 0.38, yield: 4.2, frequency: 'quarterly' },
  'TSLA': { annual: 0, quarterly: 0, yield: 0, frequency: 'quarterly' },
  'TJX': { annual: 1.20, quarterly: 0.30, yield: 1.2, frequency: 'quarterly' },
  'RCL': { annual: 2.60, quarterly: 0.65, yield: 1.4, frequency: 'quarterly' },
  'CCL': { annual: 0, quarterly: 0, yield: 0, frequency: 'quarterly' },
  
  // Materials
  'DD': { annual: 1.28, quarterly: 0.32, yield: 1.6, frequency: 'quarterly' },
  'DOW': { annual: 2.80, quarterly: 0.70, yield: 5.1, frequency: 'quarterly' },
  'LYB': { annual: 4.20, quarterly: 1.05, yield: 4.8, frequency: 'quarterly' },
  'FCX': { annual: 2.00, quarterly: 0.50, yield: 4.9, frequency: 'quarterly' },
  'NEM': { annual: 1.60, quarterly: 0.40, yield: 4.2, frequency: 'quarterly' },
  'NUE': { annual: 2.00, quarterly: 0.50, yield: 1.2, frequency: 'quarterly' },
  'STLD': { annual: 1.20, quarterly: 0.30, yield: 0.9, frequency: 'quarterly' },
  'PKG': { annual: 4.00, quarterly: 1.00, yield: 2.6, frequency: 'quarterly' },
  'IP': { annual: 2.20, quarterly: 0.55, yield: 6.8, frequency: 'quarterly' },
  'APD': { annual: 6.24, quarterly: 1.56, yield: 2.1, frequency: 'quarterly' },
  'LIN': { annual: 5.20, quarterly: 1.30, yield: 1.2, frequency: 'quarterly' },
  'ECL': { annual: 2.04, quarterly: 0.51, yield: 0.9, frequency: 'quarterly' },
  
  // Real Estate & REITs
  'ARCC': { annual: 2.64, quarterly: 0.66, yield: 12.0, frequency: 'quarterly' },
  'O': { annual: 3.06, quarterly: 0.765, yield: 5.1, frequency: 'monthly' },
  'MAIN': { annual: 2.64, quarterly: 0.66, yield: 5.4, frequency: 'quarterly' },
  'STAG': { annual: 1.68, quarterly: 0.42, yield: 4.2, frequency: 'quarterly' },
  'PLD': { annual: 2.64, quarterly: 0.66, yield: 2.1, frequency: 'quarterly' },
  'EXR': { annual: 7.00, quarterly: 1.75, yield: 3.1, frequency: 'quarterly' },
  'PSA': { annual: 8.00, quarterly: 2.00, yield: 2.8, frequency: 'quarterly' },
  'AMT': { annual: 6.16, quarterly: 1.54, yield: 3.1, frequency: 'quarterly' },
  'CCI': { annual: 5.68, quarterly: 1.42, yield: 4.8, frequency: 'quarterly' },
  'EQIX': { annual: 12.32, quarterly: 3.08, yield: 1.5, frequency: 'quarterly' },
  'DLR': { annual: 4.88, quarterly: 1.22, yield: 3.2, frequency: 'quarterly' },
  'VTR': { annual: 1.88, quarterly: 0.47, yield: 4.5, frequency: 'quarterly' },
  'WELL': { annual: 2.44, quarterly: 0.61, yield: 2.9, frequency: 'quarterly' },
  'AVB': { annual: 6.28, quarterly: 1.57, yield: 2.8, frequency: 'quarterly' },
  'EQR': { annual: 2.58, quarterly: 0.645, yield: 3.5, frequency: 'quarterly' },
  'MAA': { annual: 4.40, quarterly: 1.10, yield: 3.2, frequency: 'quarterly' },
  'ESS': { annual: 11.00, quarterly: 2.75, yield: 3.8, frequency: 'quarterly' },
  'UDR': { annual: 1.52, quarterly: 0.38, yield: 3.6, frequency: 'quarterly' },
  'CPT': { annual: 1.52, quarterly: 0.38, yield: 1.1, frequency: 'quarterly' },
  'HST': { annual: 0.84, quarterly: 0.21, yield: 4.9, frequency: 'quarterly' },
  'FRT': { annual: 3.36, quarterly: 0.84, yield: 2.8, frequency: 'quarterly' },
  'REG': { annual: 2.52, quarterly: 0.63, yield: 3.7, frequency: 'quarterly' },
  'BXP': { annual: 4.20, quarterly: 1.05, yield: 5.8, frequency: 'quarterly' },
  'KIM': { annual: 0.92, quarterly: 0.23, yield: 4.3, frequency: 'quarterly' },
  
  // European Dividend Stocks
  'ASML': { annual: 6.40, quarterly: 1.60, yield: 0.9, frequency: 'quarterly' },
  'NESN': { annual: 3.00, quarterly: 0.75, yield: 2.8, frequency: 'quarterly' },
  'NOVN': { annual: 3.10, quarterly: 0.775, yield: 3.5, frequency: 'quarterly' },
  'ROG': { annual: 9.60, quarterly: 2.40, yield: 2.8, frequency: 'quarterly' },
  'SAP': { annual: 2.20, quarterly: 0.55, yield: 1.6, frequency: 'quarterly' },
  'SHEL': { annual: 2.68, quarterly: 0.67, yield: 5.4, frequency: 'quarterly' },
  'BP': { annual: 0.28, quarterly: 0.07, yield: 5.8, frequency: 'quarterly' },
  'VOD': { annual: 0.09, quarterly: 0.0225, yield: 10.2, frequency: 'quarterly' },
  'UNVR': { annual: 1.96, quarterly: 0.49, yield: 3.4, frequency: 'quarterly' },
  'TTE': { annual: 3.20, quarterly: 0.80, yield: 5.2, frequency: 'quarterly' },
  'ENGI': { annual: 0.85, quarterly: 0.2125, yield: 6.8, frequency: 'quarterly' },
  'OR': { annual: 3.20, quarterly: 0.80, yield: 4.1, frequency: 'quarterly' },
  'SAN': { annual: 0.40, quarterly: 0.10, yield: 8.9, frequency: 'quarterly' },
  'BBVA': { annual: 0.29, quarterly: 0.0725, yield: 4.2, frequency: 'quarterly' },
  'BNP': { annual: 3.68, quarterly: 0.92, yield: 5.8, frequency: 'quarterly' },
  'ING': { annual: 0.72, quarterly: 0.18, yield: 4.9, frequency: 'quarterly' },
  'DTE': { annual: 0.64, quarterly: 0.16, yield: 3.1, frequency: 'quarterly' },
  'ENI': { annual: 0.88, quarterly: 0.22, yield: 6.2, frequency: 'quarterly' },
  
  // Major ETFs with Dividends
  'SPY': { annual: 6.57, quarterly: 1.6425, yield: 1.3, frequency: 'quarterly' },
  'VTI': { annual: 3.46, quarterly: 0.865, yield: 1.3, frequency: 'quarterly' },
  'VOO': { annual: 5.55, quarterly: 1.3875, yield: 1.3, frequency: 'quarterly' },
  'QQQ': { annual: 2.23, quarterly: 0.5575, yield: 0.5, frequency: 'quarterly' },
  'IWM': { annual: 3.31, quarterly: 0.8275, yield: 1.4, frequency: 'quarterly' },
  'EFA': { annual: 2.38, quarterly: 0.595, yield: 3.2, frequency: 'quarterly' },
  'VEA': { annual: 1.36, quarterly: 0.34, yield: 2.7, frequency: 'quarterly' },
  'IEMG': { annual: 1.23, quarterly: 0.3075, yield: 2.4, frequency: 'quarterly' },
  'VWO': { annual: 1.90, quarterly: 0.475, yield: 4.1, frequency: 'quarterly' },
  'SCHD': { annual: 2.91, quarterly: 0.7275, yield: 3.6, frequency: 'quarterly' },
  'VYM': { annual: 3.27, quarterly: 0.8175, yield: 2.8, frequency: 'quarterly' },
  'NOBL': { annual: 2.18, quarterly: 0.545, yield: 1.9, frequency: 'quarterly' },
  'VIG': { annual: 2.74, quarterly: 0.685, yield: 1.7, frequency: 'quarterly' },
  'DGRO': { annual: 1.42, quarterly: 0.355, yield: 1.9, frequency: 'quarterly' },
  'HDV': { annual: 3.65, quarterly: 0.9125, yield: 3.4, frequency: 'quarterly' },
  'DVY': { annual: 3.89, quarterly: 0.9725, yield: 3.4, frequency: 'quarterly' },
  'SPHD': { annual: 1.87, quarterly: 0.4675, yield: 4.1, frequency: 'quarterly' },
  'SCHY': { annual: 1.42, quarterly: 0.355, yield: 2.8, frequency: 'quarterly' },
  'SPYD': { annual: 1.84, quarterly: 0.46, yield: 4.9, frequency: 'quarterly' },
  'DIVO': { annual: 0.45, quarterly: 0.1125, yield: 3.8, frequency: 'quarterly' },
  'JEPI': { annual: 2.87, quarterly: 0.7175, yield: 5.2, frequency: 'quarterly' },
  'JEPQ': { annual: 2.15, quarterly: 0.5375, yield: 4.1, frequency: 'quarterly' },
  'SPLG': { annual: 1.82, quarterly: 0.455, yield: 1.3, frequency: 'quarterly' },
  'VT': { annual: 2.08, quarterly: 0.52, yield: 1.9, frequency: 'quarterly' },
  'VXUS': { annual: 1.85, quarterly: 0.4625, yield: 3.1, frequency: 'quarterly' },
  
  // Non-dividend paying stocks (for clarity)
  'GOOGL': { annual: 0, quarterly: 0, yield: 0, frequency: 'quarterly' },
  'GOOG': { annual: 0, quarterly: 0, yield: 0, frequency: 'quarterly' },
  'AMZN': { annual: 0, quarterly: 0, yield: 0, frequency: 'quarterly' },
  'META': { annual: 2.00, quarterly: 0.50, yield: 0.4, frequency: 'quarterly' },
  'NVDA': { annual: 0.16, quarterly: 0.04, yield: 0.02, frequency: 'quarterly' },
  'NFLX': { annual: 0, quarterly: 0, yield: 0, frequency: 'quarterly' },
  'BRK.B': { annual: 0, quarterly: 0, yield: 0, frequency: 'quarterly' },
  'CRM': { annual: 0, quarterly: 0, yield: 0, frequency: 'quarterly' },
  'UBER': { annual: 0, quarterly: 0, yield: 0, frequency: 'quarterly' },
  'LYFT': { annual: 0, quarterly: 0, yield: 0, frequency: 'quarterly' },
  'ZOOM': { annual: 0, quarterly: 0, yield: 0, frequency: 'quarterly' },
  'ZM': { annual: 0, quarterly: 0, yield: 0, frequency: 'quarterly' },
  'SPOT': { annual: 0, quarterly: 0, yield: 0, frequency: 'quarterly' },
  'SQ': { annual: 0, quarterly: 0, yield: 0, frequency: 'quarterly' },
  'PYPL': { annual: 0, quarterly: 0, yield: 0, frequency: 'quarterly' },
  'SHOP': { annual: 0, quarterly: 0, yield: 0, frequency: 'quarterly' },
  'ROKU': { annual: 0, quarterly: 0, yield: 0, frequency: 'quarterly' },
  'TWLO': { annual: 0, quarterly: 0, yield: 0, frequency: 'quarterly' },
  'OKTA': { annual: 0, quarterly: 0, yield: 0, frequency: 'quarterly' },
  'SNOW': { annual: 0, quarterly: 0, yield: 0, frequency: 'quarterly' },
  'PLTR': { annual: 0, quarterly: 0, yield: 0, frequency: 'quarterly' },
  'ISRG': { annual: 0, quarterly: 0, yield: 0, frequency: 'quarterly' },
  'VRTX': { annual: 0, quarterly: 0, yield: 0, frequency: 'quarterly' },
  'REGN': { annual: 0, quarterly: 0, yield: 0, frequency: 'quarterly' }
};
