// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tngtalojrxengqqrkcwl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRuZ3RhbG9qcnhlbmdxcXJrY3dsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MDY5NDIsImV4cCI6MjA2MjE4Mjk0Mn0.diBCjpGx-zU5Sj-gQP0AmZUeqPBxkLXTOIR_ecesqks";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);